# Generated by Django 5.2.14 on 2026-06-02 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Tipo de entidad')),
                ('entity_id', models.CharField(max_length=255, verbose_name='ID de entidad')),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('share', 'Compartir'), ('revoke', 'Revocar'), ('invite', 'Invitación'), ('purchase', 'Compra'), ('upload', 'Carga')], max_length=20, verbose_name='Acción')),
                ('before_data', models.JSONField(blank=True, null=True, verbose_name='Datos anteriores')),
                ('after_data', models.JSONField(blank=True, null=True, verbose_name='Datos posteriores')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'verbose_name_plural': 'Eventos de auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='core_audite_entity__e1955d_idx'), models.Index(fields=['created_at'], name='core_audite_created_9a257b_idx'), models.Index(fields=['actor'], name='core_audite_actor_i_ff084a_idx')],
            },
        ),
    ]
