# Generated by Django 5.2.14 on 2026-06-02 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('is_system', models.BooleanField(default=False, verbose_name='es del sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='items.category', verbose_name='categoría padre')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('normalized_name', models.CharField(db_index=True, max_length=200, verbose_name='nombre normalizado')),
                ('default_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='unidad por defecto')),
                ('is_frequent', models.BooleanField(default=False, verbose_name='frecuente')),
                ('owner_scope', models.CharField(choices=[('global', 'Global'), ('user', 'Usuario'), ('list', 'Lista')], default='global', max_length=20, verbose_name='ámbito')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_templates', to='items.category', verbose_name='categoría por defecto')),
            ],
            options={
                'verbose_name': 'plantilla de producto',
                'verbose_name_plural': 'plantillas de producto',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('quantity', models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='cantidad')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='unidad')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='precio estimado')),
                ('actual_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='precio real')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('bought', 'Comprado'), ('skipped', 'Saltado'), ('unavailable', 'No disponible')], default='pending', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_items', to='items.category', verbose_name='categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.shoppinglist', verbose_name='lista')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_items', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_items', to='items.producttemplate', verbose_name='plantilla')),
            ],
            options={
                'verbose_name': 'ítem de lista',
                'verbose_name_plural': 'ítems de lista',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='producttemplate',
            index=models.Index(fields=['normalized_name'], name='items_produ_normali_dfd27e_idx'),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['list', 'status', 'category'], name='items_listi_list_id_d736ae_idx'),
        ),
    ]
