# Generated by Django 5.2.14 on 2026-06-02 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('frequency_type', models.CharField(choices=[('weekly', 'Semanal'), ('monthly', 'Mensual'), ('custom', 'Personalizado'), ('one_off', 'Una vez')], default='weekly', max_length=20, verbose_name='tipo de frecuencia')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('archived', 'Archivada')], default='active', max_length=20, verbose_name='estado')),
                ('share_token', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='token de compartición')),
                ('share_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expiración del token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_lists', to=settings.AUTH_USER_MODEL, verbose_name='propietario')),
            ],
            options={
                'verbose_name': 'lista de compras',
                'verbose_name_plural': 'listas de compras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('editor', 'Editor'), ('viewer', 'Espectador')], default='viewer', max_length=20, verbose_name='rol')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='invitado en')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='aceptado en')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='invitado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='lists.shoppinglist', verbose_name='lista')),
            ],
            options={
                'verbose_name': 'miembro de lista',
                'verbose_name_plural': 'miembros de lista',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='token')),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Espectador')], default='viewer', max_length=20, verbose_name='rol')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('expires_at', models.DateTimeField(verbose_name='expira en')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invitations', to=settings.AUTH_USER_MODEL, verbose_name='invitado por')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='lists.shoppinglist', verbose_name='lista')),
            ],
            options={
                'verbose_name': 'invitación',
                'verbose_name_plural': 'invitaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['owner', 'status'], name='lists_shopp_owner_i_75953b_idx'),
        ),
        migrations.AddIndex(
            model_name='listmember',
            index=models.Index(fields=['list', 'user'], name='lists_listm_list_id_bb25e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listmember',
            unique_together={('list', 'user')},
        ),
    ]
