# Generated by Django 5.2.14 on 2026-06-02 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('lists', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('purchase_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de compra')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='subtotal')),
                ('discount_total', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='descuento total')),
                ('tax_total', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='impuesto total')),
                ('total_paid', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='total pagado')),
                ('currency', models.CharField(default='CLP', max_length=3, verbose_name='moneda')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='comprado por')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='lists.shoppinglist', verbose_name='lista de compras')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='vendors.vendor', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'compra',
                'verbose_name_plural': 'compras',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='nombre del producto')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='precio unitario')),
                ('line_total', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='total línea')),
                ('estimated_line_total', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='total estimado')),
                ('difference_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='diferencia')),
                ('list_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_lines', to='items.listitem', verbose_name='ítem de lista')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchase', verbose_name='compra')),
            ],
            options={
                'verbose_name': 'línea de compra',
                'verbose_name_plural': 'líneas de compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='número de boleta')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='emitido en')),
                ('file', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='archivo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notas')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='purchases.purchase', verbose_name='compra')),
            ],
            options={
                'verbose_name': 'boleta',
                'verbose_name_plural': 'boletas',
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['shopping_list', 'vendor', 'purchase_date'], name='purchases_p_shoppin_aead8b_idx'),
        ),
    ]
