# Generated by Django 5.2.14 on 2026-06-02 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='inicio del período')),
                ('period_end', models.DateField(verbose_name='fin del período')),
                ('budgeted_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='monto presupuestado')),
                ('actual_spent', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='gasto real')),
                ('difference', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='diferencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_snapshots', to='lists.shoppinglist', verbose_name='lista de compras')),
            ],
            options={
                'verbose_name': 'instantánea de presupuesto',
                'verbose_name_plural': 'instantáneas de presupuesto',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['shopping_list', 'period_start'], name='reports_bud_shoppin_c80d96_idx')],
            },
        ),
    ]
