# Generated by Django 5.2.14 on 2026-06-02 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('address', models.TextField(blank=True, null=True, verbose_name='dirección')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='ciudad')),
                ('vendor_type', models.CharField(choices=[('supermarket', 'Supermercado'), ('fair', 'Feria'), ('store', 'Tienda'), ('other', 'Otro')], default='other', max_length=20, verbose_name='tipo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='vendors_ven_name_0d60a8_idx')],
            },
        ),
    ]
